set nocompatible

" Automatic reloading of .nvimrc
autocmd! bufwritepost nvimrc source %

" Set backup directory
set backupdir=~/.local/share/nvim/swap

" Reload file if it was changed
set autoread

" Set backspace behavior
set backspace=indent,eol,start

" Colors
set background=dark

" Indentation
set smartindent

set tabstop=4
set shiftwidth=4
set expandtab

autocmd FileType ruby setlocal tabstop=2
autocmd FileType ruby setlocal shiftwidth=2

" Set mapleader to comma
let mapleader = ','

" Show commands int bottom right corner
set showcmd

" Easy sorting of selected lines
vnoremap <Leader>s :sort<CR>

" Make files should use tabs instead of spaces
autocmd FileType make setlocal noexpandtab

" Cursor
set cursorline

" Bind Ctrl + [h,j,k,l] for quick window movement
map <c-h> <c-w>h
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l

" Bind move command
nnoremap ∆ :m .+1<CR>==
nnoremap ˚ :m .-2<CR>==
inoremap ∆ <Esc>:m .+1<CR>==gi
inoremap ˚ <Esc>:m .-2<CR>==gi
vnoremap ∆ :m '>+1<CR>gv=gv
vnoremap ˚ :m '<-2<CR>gv=gv

" Remove trailing spaces
nmap <Leader><space> :%s/\s\+$<cr>

" Highlight searched word
set incsearch

" Ignore case
set ignorecase
set smartcase

" Show vertical line on 80 column
set colorcolumn=85

" GUI options
set guioptions+=LlRrb
set guioptions-=LlRrb

" Display ruler on the right side of the status line at the bottom of the window
set ruler

" Set relative numbers with current line number on cursor line
set relativenumber
set number
" Switch to absolute numbers in Insert mode
autocmd InsertEnter * set number norelativenumber
" Switch back to relative numbers in Normal mode
autocmd InsertLeave * set number relativenumber

" Better indenting of code block
vnoremap < <gv
vnoremap > >gv

" Disable mouse
set mouse=

call plug#begin('~/.config/nvim/plugged')

" Vundle can manage itself
Plug 'gmarik/Vundle.vim'

" Library needed by some plugins
Plug 'L9'

" Fuzzy finder for files and buffers
Plug 'kien/ctrlp.vim'

" Quick navigation for files/folders in current folder
Plug 'scrooloose/nerdtree'

" Quick switching between source and header file
Plug 'a.vim'

" Check source code syntax
Plug 'benekastah/neomake'

" Easy managing for snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" Autocompletion for quotes, parentheses etc
Plug 'Raimondi/delimitMate'

" Groovy syntax for .gradle files
Plug 'tfnico/vim-gradle'

" Changes Vim working directory to project root
Plug 'airblade/vim-rooter'

" Displays tags in a window
Plug 'majutsushi/tagbar'

" Git wrapper
Plug 'tpope/vim-fugitive'

" Quick (un)comment line(s)
Plug 'scrooloose/nerdcommenter'

" Jellybeans
"Plug 'nanotech/jellybeans.vim'

" Solarized
Plug 'altercation/vim-colors-solarized'

" Airline - like powerline
Plug 'bling/vim-airline'

" Dash app helper
Plug 'rizzatti/dash.vim'

" Swift
Plug 'keith/swift.vim'

call plug#end()

" Run everytime neomake
autocmd! BufWritePost * Neomake

" Color scheme
colorscheme solarized

" Syntax highlighting
filetype off
filetype plugin indent on
syntax on

" Delimitmate config
let delimitMate_expand_cr = 1
imap <expr> <CR> pumvisible() ? "\<c-y>" : "<Plug>delimitMateCR"

" Ctrlp should ignore some hidden folders and binary/temp files
let g:ctrlp_custom_ignore = {
            \ 'dir':  '\v[\/]\.(git|hg|svn)$',
            \ 'file': '\v\.(pyc|swp|so|class|zip|o)$',
            \ }


" NERDTree
let NERDTreeIgnore = ['\.pyc$', '\.o$', '\.class$']
" Map Ctrl + x to open NERDTree file explorer
nnoremap <C-x> :NERDTreeToggle<CR>
inoremap <C-x> <Esc>:NERDTreeToggle<CR>

" Airline settings
let g:airline_powerline_fonts = 1
let g:airline_theme = 'solarized'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
set laststatus=2

" Fugitive mapping
nmap <silent> <leader>gs :Gstatus<cr>
nmap <silent> <leader>gd :Gdiff<cr>
nmap <silent> <leader>gb :Gblame<cr>

" TagBar
nmap <F8> :TagbarOpenAutoClose<CR>

" Equal sizes of splits when window resize
au VimResized * :wincmd =

" Highlight trailing whitespaces
highlight ExtraWhitespace ctermbg=red
au BufWinEnter * match ExtraWhitespace /\s\+$/
" Show trailing whitespace as dot
" Show tab character as >-
set list
set listchars=trail:·,tab:>-

" Ultisnips
let g:UltiSnipsExpandTrigger = '<tab>'

" Scroll faster
nnoremap <c-e> 5<c-e>
nnoremap <c-y> 5<c-y>

