# Update global variables
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# FZF settings
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always --theme Dracula {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_ALT_C_OPTS="
  --walker-skip .git,node_modules,target,Library
  --preview 'tree -L 2 -C {}'"
export FZF_TMUX_OPTS='-p80%,60%'

# Node Version Manager - https://github.com/nvm-sh/nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Plugins 
plugins=(
  macos
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# load zsh-completions
autoload -U compinit && compinit

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Aliases
alias v="nvim"

alias gs="git status"
alias ga="git add ."
alias gcm="git commit -m "
alias gp="git push"

# Add fzf
eval "$(fzf --zsh)"

# Starship terminal
eval "$(starship init zsh)"

